import pathlib
import pandas as pd
import argparse

# Generates plots based on the CSV generated by evaluate_feature_attribution_with_ground_truth.py.
# CSV file names are expected to be named 'runX Y.csv' for a run number X on dataset Y.

parser = argparse.ArgumentParser(description="Runs different explanation approaches")

parser.add_argument(
    "--results_path",
    required=True,
    type=str,
    help="Path to the location of the csv files to be processed",
)
parser.add_argument(
    "--save_path",
    required=True,
    type=str,
    help="Path to the location to which the plots will be saved",
)
parser.add_argument(
    "--dataset",
    type=str,
    required=True,
    choices=["MSLR-WEB10K", "MQ2008"],
    help="The dataset to use MQ2008 or MSLR-WEB10K",
)

parser.add_argument(
    "--n_runs",
    type=int,
    required=True,
    help="Number of runs to average",
)

args = parser.parse_args()

# path to results csv
filepath = pathlib.Path(args.results_path)
savepath = pathlib.Path(args.save_path)
# number of runs to average
n_runs = args.n_runs
# dataset name
dataset = args.dataset
runs = []


for i in range(n_runs):
    runs.append(pd.read_csv(filepath / "run{} {}.csv".format(i+1, dataset)))

total = pd.concat(runs)
mean = total.groupby("approach").mean()

mean = mean.reset_index()

mean[['approach', 'at']] = mean.approach.str.split("@", expand = True)


metrics = [ "Pre_ken", "Del_ken", "Pre_exp", "Del_exp"]
proper_names = ["Preservation kendalltau", "Deletion kendalltau", \
             "Preservation exposure difference", "Deletion exposure difference"]

metric_dfs = []

colours = {'greedy_iter': '#ffd166', 'random': '#a8d48a', 'rankingshapK': '#d6335c', 'rankingshapW': '#993399', 'greedy_iter_full': '#222222', 'pointwise_lime': '#99d6c2', 'pointwise_shap': '#bab2f7', 'rankinglime': '#f0b2c2'}

for metric in metrics:
    metric_dfs.append(mean[["approach", 'at', metric]])


    for k in [1,3,5,7,10]:
        metric_dfs[-1][str(k)] = metric_dfs[-1].loc[metric_dfs[-1]['at'] == str(k), [metric]]


    metric_dfs[-1] = metric_dfs[-1].drop(['at', metric], axis= 1)

    metric_dfs[-1] = metric_dfs[-1].groupby('approach').sum()
    

i = 0
for i in range(4):
    if i%2 == 1:
        metric_dfs[i] = metric_dfs[i] * -1
    plot = metric_dfs[i].T.plot(linewidth=2, color = [colours.get(name, '#333333') for name in metric_dfs[i].T.columns])
    plot = plot.set_title(proper_names[i] + " " + dataset)


    plot.figure.savefig(savepath / "{} {}.jpg".format(metrics[i], dataset))
